version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/app:/app
    env_file: 
      - .env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./web
    ports:
      - "3000:3000"
